version: '3'

services:
  jumpbox:
    image: alpine
    # Keep this running
    command: tail -F /dev/null

  airflow:
    build:
      context: airflow/
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_HOME: /opt/airflow

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password123
    ports:
      - "9090:5432"
    links:
      - airflow
      - jumpbox
      - simple-microservice

  simple-microservice:
      build:
        context: simple-microservice
      command: tail -f /dev/null