version: '3'

services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  microservice:
    build:
      context: simple-microservice
    ports:
      - "9090:9090"
    links:
      - postgres
    depends_on:
      - postgres

  airflow:
    build:
      context: airflow/
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_HOME: /opt/airflow
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
    links:
      - postgres
      - microservice
    depends_on:
      - postgres
      - microservice

