version: '3'

services:
  jumpbox:
    image: alpine
    command: tail -F anything

  airflow:
    build:
      context: airflow/
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_HOME: /opt/airflow

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5439:5439"
    links:
      - airflow
      - jumpbox

  simple-microservice:
      build:
        context: simple-microservice
