version: '3'

services:
  # Backend database
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password123
    # Expose only to other containers
    expose:
      - 5432

  # Simple Clojure microservice
  microservice:
    build:
      context: simple-microservice
    depends_on:
      - postgres
    restart: always
    # Expose only to other containers
    expose:
      - 9090

  # Dataflow manager with Apache Airflow
  airflow:
    build:
      context: airflow/
    restart: always
    # Map port to host machine
    ports:
      - 8080:8080
    # Environment variables
    environment:
      AIRFLOW_HOME: /opt/airflow
      POSTGRES_CONN_ID: postgres://postgres:password123@postgres:5432/db
      HTTP_CONN_ID: http://microservice:9090
    links:
      - postgres
      - microservice

