version: '3'

services:
  # Backend database
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password123
    # Expose only to other containers
    expose:
      - 5432

  # Simple Clojure Microservice
  microservice:
    build:
      context: simple-microservice
    depends_on:
      - postgres
    restart: always
    ports:
      - 9090:9090

  # Dataflow manager with Apache Airflow
  airflow:
    build:
      context: airflow/
    restart: always
    # Map port to host machine
    ports:
      - 8080:8080
    # Environment variables
    environment:
      AIRFLOW_HOME: /opt/airflow
      # See how to manage connections: https://airflow.readthedocs.io/en/stable/howto/manage-connections.html
      AIRFLOW_CONN_POSTGRES_MASTER: postgres://postgres:password123@postgres:5432/db
      AIRFLOW_CONN_HTTP_MASTER: http://microservice:9090
    links:
      - postgres
      - microservice

