version: '3'

services:
  jumpbox:
    image: postgres
    command: tail -F anything
    # psql -h postgres -U postgres

  airflow:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: puckel/docker-airflow
    ports:
    - "8080:8080"
    volumes:
    - .:/opt/airflow-samples
    environment:
      - AIRFLOW_HOME=/opt/airflow-samples/airflow
    command: bash /opt/airflow-samples/airflow_entrypoint.sh

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5439:5439"
    links:
      - airflow
      - jumpbox

