version: '3'

services:
  airflow:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: puckel/docker-airflow
    ports:
    - "8080:8080"
    volumes:
    - .:/opt/airflow-samples
    links:
      - postgres
    command: ["cd","/opt/airflow-samples","&&", "make", "webserver"]

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5439:5439"
