version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    volumes:
    - .:/opt/airflow-samples
    command: ["cd","/opt/airflow-samples","&&", "make", "webserver"]


