version: '3'

services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  airflow:
    build:
      context: airflow/
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_HOME: /opt/airflow
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
    links:
      - postgres
    depends_on:
      - postgres

  simple-microservice:
      build:
        context: simple-microservice
      # Expose internal 9090 for microservice
      expose:
        - 9090
      # Bind local machine 9191 to container 9090 9191:9090
      ports:
        - "9090:9090"
      links:
        - postgres
        - airflow
      depends_on:
        - postgres

  # For querying the database manually
  psqlclient:
    image: postgres:11.1
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGPASSWORD: password123
